child/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  get "iframe", to: "iframe#index"
  get "first_party_cookie", to: "first_party_cookie#index"
  root "iframe#index"
end

child/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

child/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

child/app/controllers/first_party_cookie_controller.rb
class FirstPartyCookieController < ApplicationController

  def index
    cookies["serverside"] = {
      value: 1,
      expires: 1.years.from_now
    }
  end
end

child/app/controllers/iframe_controller.rb
class IframeController < ApplicationController
  layout "iframe"

  def index
  end

end

child/app/helpers/application_helper.rb
module ApplicationHelper
end

child/app/helpers/first_party_cookie_helper.rb
module FirstPartyCookieHelper
end

child/app/helpers/iframe_helper.rb
module IframeHelper
end

child/app/views/first_party_cookie/index.html.erb
<%# <input type="checkbox" name="agree" value="Agree"> Yes, I agree to earn rewards for a referral. %>

<a href="http://parent.test/" class="button">Refer Now</a>

child/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Child</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

child/app/views/layouts/iframe.html.erb
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <title>Child Domain</title>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/js-cookie/2.2.0/js.cookie.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jschannel/1.0.0-git-commit1-8c4f7eb/jschannel.min.js"></script>
    </head>
    <body>
        <base target="_parent">

        <div>
            Cookies: <ul id="cookie-iframe-data"></ul>
        </div>

        <%= link_to "Refer Now", first_party_cookie_url %>
        <button onClick="onLoginClick()">Submit</button>
        <br>
        <script type="text/javascript">
            var chan = Channel.build({
                window: window.parent,
                origin: "*",
                scope: "testScope"
            });

            // Other end of the JSChannel call
            chan.bind("reverse", function(trans, s) {
                return s.split("").reverse().join("");
            });

            document.getElementById('cookie-iframe-data').innerHTML=listCookies()
            function listCookies() {
                var theCookies = document.cookie.split(';');
                var aString = '';
                for (var i = 1 ; i <= theCookies.length; i++) {
                    aString += i + ' ' + theCookies[i-1] + "\n";
            }
                return aString;
            }


            let onLoginClick = function(trans, params) {
                document.hasStorageAccess().then(hasAccess => {
                    if (!hasAccess) {
                        console.log("no access - requesting access");
                        return document.requestStorageAccess();
                    }
                }).then(_ => {
                    document.hasStorageAccess().then(hasAccess => {
                        console.log("hasAccess:", hasAccess);
                        // window.localStorage.setItem('foo', 'bar');
                        document.cookie = 'iframecookie=test; expires=Thu, 01 Jan 2022 00:00:00 UTC; path=/'
                        console.log(document.cookie)
                    })
                }).catch((err) => {
                    console.log("hasStorageAccess() failed", err);
                });
            };
        </script>
    </body>
</html>